/**
 * Internationalization System
 * Multi-language support with automatic detection and switching
 * Supports 13 languages: en, es, fr, de, zh, ja, ar, pt, ko, it, ru, hi, tr
 */

const I18n = {
    currentLanguage: 'en',
    translations: {},
    supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'ar', 'pt', 'ko', 'it', 'ru', 'hi', 'tr'],

    /** Initialize internationalization */
    init() {
        this.detectLanguage();
        this.loadTranslations();
        this.applyTranslations();
        this.addLanguageSwitcher();
    },

    /** Detect user's preferred language */
    detectLanguage() {
        const savedLanguage = localStorage.getItem('preferredLanguage');
        if (savedLanguage && this.supportedLanguages.indexOf(savedLanguage) !== -1) {
            this.currentLanguage = savedLanguage;
            return;
        }
        const browserLanguage = navigator.language || navigator.userLanguage || 'en';
        const languageCode = browserLanguage.split('-')[0];
        if (this.supportedLanguages.indexOf(languageCode) !== -1) {
            this.currentLanguage = languageCode;
        }
        localStorage.setItem('preferredLanguage', this.currentLanguage);
    },

    /** Load translations for all supported languages */
    loadTranslations() {
        this.translations = {
            en: {
                'app.title': 'Ambulance Scheduling System',
                'app.welcome': 'Welcome',
                'app.loading': 'Loading...',
                'app.error': 'Error',
                'app.success': 'Success',
                'app.cancel': 'Cancel',
                'app.save': 'Save',
                'app.delete': 'Delete',
                'app.edit': 'Edit',
                'app.close': 'Close',
                'app.submit': 'Submit',
                'app.search': 'Search',
                'app.confirm': 'Confirm',
                'app.back': 'Back',
                'app.next': 'Next',
                'app.yes': 'Yes',
                'app.no': 'No',
                'auth.login': 'Login',
                'auth.logout': 'Logout',
                'auth.username': 'Username',
                'auth.password': 'Password',
                'auth.login.success': 'Login successful',
                'auth.login.failed': 'Login failed',
                'auth.logout.success': 'Logged out successfully',
                'dashboard.title': 'Dashboard',
                'dashboard.welcome': 'Welcome back',
                'dashboard.overview': 'Overview',
                'schedule.title': 'Schedule',
                'schedule.create': 'Create Schedule',
                'schedule.view': 'View Schedule',
                'schedule.draft': 'Draft Schedules',
                'schedule.published': 'Published Schedules',
                'schedule.archived': 'Past Schedules',
                'schedule.week': 'Week',
                'schedule.day': 'Day',
                'schedule.night': 'Night',
                'shift.24hour': '24-Hour Shift',
                'shift.day': 'Day Shift',
                'shift.night': 'Night Shift',
                'shift.evening': 'Evening Shift',
                'crew.title': 'Crew',
                'crew.create': 'Create Crew',
                'crew.manage': 'Manage Crew',
                'crew.member': 'Crew Member',
                'crew.templates': 'Crew Templates',
                'user.title': 'User',
                'user.admin': 'Admin',
                'user.boss': 'Boss',
                'user.paramedic': 'Paramedic',
                'user.emt': 'EMT',
                'user.management': 'User Management',
                'timeoff.title': 'Time Off',
                'timeoff.request': 'Request Time Off',
                'timeoff.approved': 'Approved',
                'timeoff.denied': 'Denied',
                'timeoff.pending': 'Pending',
                'notification.title': 'Notifications',
                'notification.new': 'New notification',
                'notification.read': 'Mark as read',
                'report.title': 'Reports',
                'report.export': 'Export Report',
                'report.download': 'Download',
                'settings.title': 'Settings',
                'settings.language': 'Language',
                'settings.theme': 'Theme',
                'nav.scheduling': 'Scheduling',
                'nav.requests': 'Requests',
                'nav.staff': 'Staff Management',
                'nav.operations': 'Operations',
                'nav.analysis': 'Analysis',
                'nav.calendar': 'Calendar View',
                'nav.trades': 'Shift Trades',
                'nav.swap': 'Swap Marketplace',
                'nav.availability': 'Availability',
                'nav.training': 'Training',
                'nav.bonus': 'Bonus Hours',
                'nav.callins': 'Emergency Call-ins',
                'nav.absences': 'Absences',
                'nav.oncall': 'On-Call Rotation',
                'nav.analytics': 'Analytics',
                'nav.history': 'Shift History',
                'nav.notes': 'Supervisor Notes',
                'nav.templates': 'Schedule Templates',
                'nav.payroll': 'Payroll',
                'nav.locations': 'Locations',
                'nav.permissions': 'Permissions',
                'error.required': 'This field is required',
                'error.invalid': 'Invalid input',
                'error.exists': 'Already exists',
                'error.notfound': 'Not found'
            },
            es: {
                'app.title': 'Sistema de Programación de Ambulancias',
                'app.welcome': 'Bienvenido',
                'app.loading': 'Cargando...',
                'app.error': 'Error',
                'app.success': 'Éxito',
                'app.cancel': 'Cancelar',
                'app.save': 'Guardar',
                'app.delete': 'Eliminar',
                'app.edit': 'Editar',
                'app.close': 'Cerrar',
                'app.submit': 'Enviar',
                'app.search': 'Buscar',
                'app.confirm': 'Confirmar',
                'app.back': 'Atrás',
                'app.next': 'Siguiente',
                'app.yes': 'Sí',
                'app.no': 'No',
                'auth.login': 'Iniciar Sesión',
                'auth.logout': 'Cerrar Sesión',
                'auth.username': 'Usuario',
                'auth.password': 'Contraseña',
                'auth.login.success': 'Inicio de sesión exitoso',
                'auth.login.failed': 'Error de inicio de sesión',
                'auth.logout.success': 'Sesión cerrada exitosamente',
                'dashboard.title': 'Panel de Control',
                'dashboard.welcome': 'Bienvenido de nuevo',
                'dashboard.overview': 'Resumen',
                'schedule.title': 'Horario',
                'schedule.create': 'Crear Horario',
                'schedule.view': 'Ver Horario',
                'schedule.draft': 'Borradores',
                'schedule.published': 'Publicados',
                'schedule.archived': 'Archivados',
                'schedule.week': 'Semana',
                'schedule.day': 'Día',
                'schedule.night': 'Noche',
                'shift.24hour': 'Turno de 24 Horas',
                'shift.day': 'Turno Diurno',
                'shift.night': 'Turno Nocturno',
                'shift.evening': 'Turno Vespertino',
                'crew.title': 'Tripulación',
                'crew.create': 'Crear Tripulación',
                'crew.manage': 'Gestionar Tripulación',
                'crew.member': 'Miembro',
                'crew.templates': 'Plantillas de Tripulación',
                'user.title': 'Usuario',
                'user.admin': 'Administrador',
                'user.boss': 'Jefe',
                'user.paramedic': 'Paramédico',
                'user.emt': 'Técnico EMT',
                'user.management': 'Gestión de Usuarios',
                'timeoff.title': 'Tiempo Libre',
                'timeoff.request': 'Solicitar Tiempo Libre',
                'timeoff.approved': 'Aprobado',
                'timeoff.denied': 'Denegado',
                'timeoff.pending': 'Pendiente',
                'notification.title': 'Notificaciones',
                'notification.new': 'Nueva notificación',
                'notification.read': 'Marcar como leído',
                'report.title': 'Informes',
                'report.export': 'Exportar Informe',
                'report.download': 'Descargar',
                'settings.title': 'Configuración',
                'settings.language': 'Idioma',
                'settings.theme': 'Tema',
                'nav.scheduling': 'Programación',
                'nav.requests': 'Solicitudes',
                'nav.staff': 'Gestión de Personal',
                'nav.operations': 'Operaciones',
                'nav.analysis': 'Análisis',
                'nav.calendar': 'Vista de Calendario',
                'nav.trades': 'Intercambio de Turnos',
                'nav.swap': 'Mercado de Intercambio',
                'nav.availability': 'Disponibilidad',
                'nav.training': 'Capacitación',
                'nav.bonus': 'Horas Extra',
                'nav.callins': 'Llamadas de Emergencia',
                'nav.absences': 'Ausencias',
                'nav.oncall': 'Rotación de Guardia',
                'nav.analytics': 'Analítica',
                'nav.history': 'Historial de Turnos',
                'nav.notes': 'Notas del Supervisor',
                'nav.templates': 'Plantillas',
                'nav.payroll': 'Nómina',
                'nav.locations': 'Ubicaciones',
                'nav.permissions': 'Permisos',
                'error.required': 'Este campo es obligatorio',
                'error.invalid': 'Entrada inválida',
                'error.exists': 'Ya existe',
                'error.notfound': 'No encontrado'
            },
            fr: {
                'app.title': 'Système de Planification Ambulancier',
                'app.welcome': 'Bienvenue',
                'app.loading': 'Chargement...',
                'app.error': 'Erreur',
                'app.success': 'Succès',
                'app.cancel': 'Annuler',
                'app.save': 'Enregistrer',
                'app.delete': 'Supprimer',
                'app.edit': 'Modifier',
                'app.close': 'Fermer',
                'app.submit': 'Soumettre',
                'app.search': 'Rechercher',
                'app.confirm': 'Confirmer',
                'app.back': 'Retour',
                'app.next': 'Suivant',
                'app.yes': 'Oui',
                'app.no': 'Non',
                'auth.login': 'Connexion',
                'auth.logout': 'Déconnexion',
                'auth.username': 'Identifiant',
                'auth.password': 'Mot de passe',
                'auth.login.success': 'Connexion réussie',
                'auth.login.failed': 'Échec de connexion',
                'auth.logout.success': 'Déconnexion réussie',
                'dashboard.title': 'Tableau de Bord',
                'dashboard.welcome': 'Bon retour',
                'dashboard.overview': 'Aperçu',
                'schedule.title': 'Planning',
                'schedule.create': 'Créer un Planning',
                'schedule.view': 'Voir le Planning',
                'schedule.draft': 'Brouillons',
                'schedule.published': 'Publiés',
                'schedule.archived': 'Archivés',
                'schedule.week': 'Semaine',
                'schedule.day': 'Jour',
                'schedule.night': 'Nuit',
                'shift.24hour': 'Garde de 24 Heures',
                'shift.day': 'Garde de Jour',
                'shift.night': 'Garde de Nuit',
                'shift.evening': 'Garde du Soir',
                'crew.title': 'Équipage',
                'crew.create': 'Créer un Équipage',
                'crew.manage': 'Gérer l\'Équipage',
                'crew.member': 'Membre',
                'crew.templates': 'Modèles d\'Équipage',
                'user.title': 'Utilisateur',
                'user.admin': 'Administrateur',
                'user.boss': 'Chef',
                'user.paramedic': 'Ambulancier',
                'user.emt': 'Technicien',
                'user.management': 'Gestion des Utilisateurs',
                'timeoff.title': 'Congés',
                'timeoff.request': 'Demander un Congé',
                'timeoff.approved': 'Approuvé',
                'timeoff.denied': 'Refusé',
                'timeoff.pending': 'En attente',
                'notification.title': 'Notifications',
                'notification.new': 'Nouvelle notification',
                'notification.read': 'Marquer comme lu',
                'report.title': 'Rapports',
                'report.export': 'Exporter le Rapport',
                'report.download': 'Télécharger',
                'settings.title': 'Paramètres',
                'settings.language': 'Langue',
                'settings.theme': 'Thème',
                'nav.scheduling': 'Planification',
                'nav.requests': 'Demandes',
                'nav.staff': 'Gestion du Personnel',
                'nav.operations': 'Opérations',
                'nav.analysis': 'Analyse',
                'nav.calendar': 'Vue Calendrier',
                'nav.trades': 'Échanges de Gardes',
                'nav.swap': 'Marché d\'Échange',
                'nav.availability': 'Disponibilité',
                'nav.training': 'Formation',
                'nav.bonus': 'Heures Supplémentaires',
                'nav.callins': 'Appels d\'Urgence',
                'nav.absences': 'Absences',
                'nav.oncall': 'Rotation d\'Astreinte',
                'nav.analytics': 'Analytique',
                'nav.history': 'Historique des Gardes',
                'nav.notes': 'Notes du Superviseur',
                'nav.templates': 'Modèles',
                'nav.payroll': 'Paie',
                'nav.locations': 'Sites',
                'nav.permissions': 'Autorisations',
                'error.required': 'Ce champ est obligatoire',
                'error.invalid': 'Entrée invalide',
                'error.exists': 'Existe déjà',
                'error.notfound': 'Non trouvé'
            },
            de: {
                'app.title': 'Rettungsdienst-Planungssystem',
                'app.welcome': 'Willkommen',
                'app.loading': 'Laden...',
                'app.error': 'Fehler',
                'app.success': 'Erfolg',
                'app.cancel': 'Abbrechen',
                'app.save': 'Speichern',
                'app.delete': 'Löschen',
                'app.edit': 'Bearbeiten',
                'app.close': 'Schließen',
                'app.submit': 'Absenden',
                'app.search': 'Suchen',
                'app.confirm': 'Bestätigen',
                'app.back': 'Zurück',
                'app.next': 'Weiter',
                'app.yes': 'Ja',
                'app.no': 'Nein',
                'auth.login': 'Anmelden',
                'auth.logout': 'Abmelden',
                'auth.username': 'Benutzername',
                'auth.password': 'Passwort',
                'auth.login.success': 'Anmeldung erfolgreich',
                'auth.login.failed': 'Anmeldung fehlgeschlagen',
                'auth.logout.success': 'Erfolgreich abgemeldet',
                'dashboard.title': 'Übersicht',
                'dashboard.welcome': 'Willkommen zurück',
                'dashboard.overview': 'Überblick',
                'schedule.title': 'Dienstplan',
                'schedule.create': 'Dienstplan erstellen',
                'schedule.view': 'Dienstplan anzeigen',
                'schedule.draft': 'Entwürfe',
                'schedule.published': 'Veröffentlicht',
                'schedule.archived': 'Archiviert',
                'schedule.week': 'Woche',
                'schedule.day': 'Tag',
                'schedule.night': 'Nacht',
                'shift.24hour': '24-Stunden-Schicht',
                'shift.day': 'Tagschicht',
                'shift.night': 'Nachtschicht',
                'shift.evening': 'Abendschicht',
                'crew.title': 'Besatzung',
                'crew.create': 'Besatzung erstellen',
                'crew.manage': 'Besatzung verwalten',
                'crew.member': 'Mitglied',
                'crew.templates': 'Besatzungsvorlagen',
                'user.title': 'Benutzer',
                'user.admin': 'Administrator',
                'user.boss': 'Vorgesetzter',
                'user.paramedic': 'Rettungssanitäter',
                'user.emt': 'Sanitäter',
                'user.management': 'Benutzerverwaltung',
                'timeoff.title': 'Urlaub',
                'timeoff.request': 'Urlaub beantragen',
                'timeoff.approved': 'Genehmigt',
                'timeoff.denied': 'Abgelehnt',
                'timeoff.pending': 'Ausstehend',
                'notification.title': 'Benachrichtigungen',
                'notification.new': 'Neue Benachrichtigung',
                'notification.read': 'Als gelesen markieren',
                'report.title': 'Berichte',
                'report.export': 'Bericht exportieren',
                'report.download': 'Herunterladen',
                'settings.title': 'Einstellungen',
                'settings.language': 'Sprache',
                'settings.theme': 'Design',
                'nav.scheduling': 'Planung',
                'nav.requests': 'Anfragen',
                'nav.staff': 'Personalverwaltung',
                'nav.operations': 'Betrieb',
                'nav.analysis': 'Analyse',
                'nav.calendar': 'Kalenderansicht',
                'nav.trades': 'Schichttausch',
                'nav.swap': 'Tauschbörse',
                'nav.availability': 'Verfügbarkeit',
                'nav.training': 'Ausbildung',
                'nav.bonus': 'Überstunden',
                'nav.callins': 'Notrufe',
                'nav.absences': 'Abwesenheiten',
                'nav.oncall': 'Bereitschaftsdienst',
                'nav.analytics': 'Analytik',
                'nav.history': 'Schichthistorie',
                'nav.notes': 'Vorgesetztennotizen',
                'nav.templates': 'Vorlagen',
                'nav.payroll': 'Gehaltsabrechnung',
                'nav.locations': 'Standorte',
                'nav.permissions': 'Berechtigungen',
                'error.required': 'Dieses Feld ist erforderlich',
                'error.invalid': 'Ungültige Eingabe',
                'error.exists': 'Existiert bereits',
                'error.notfound': 'Nicht gefunden'
            },
            zh: {
                'app.title': '救护车调度系统',
                'app.welcome': '欢迎',
                'app.loading': '加载中...',
                'app.error': '错误',
                'app.success': '成功',
                'app.cancel': '取消',
                'app.save': '保存',
                'app.delete': '删除',
                'app.edit': '编辑',
                'app.close': '关闭',
                'app.submit': '提交',
                'app.search': '搜索',
                'app.confirm': '确认',
                'app.back': '返回',
                'app.next': '下一步',
                'app.yes': '是',
                'app.no': '否',
                'auth.login': '登录',
                'auth.logout': '退出',
                'auth.username': '用户名',
                'auth.password': '密码',
                'auth.login.success': '登录成功',
                'auth.login.failed': '登录失败',
                'auth.logout.success': '已成功退出',
                'dashboard.title': '控制面板',
                'dashboard.welcome': '欢迎回来',
                'dashboard.overview': '概览',
                'schedule.title': '排班',
                'schedule.create': '创建排班',
                'schedule.view': '查看排班',
                'schedule.draft': '草稿',
                'schedule.published': '已发布',
                'schedule.archived': '已归档',
                'schedule.week': '周',
                'schedule.day': '日',
                'schedule.night': '夜',
                'shift.24hour': '24小时班',
                'shift.day': '白班',
                'shift.night': '夜班',
                'shift.evening': '晚班',
                'crew.title': '班组',
                'crew.create': '创建班组',
                'crew.manage': '管理班组',
                'crew.member': '成员',
                'crew.templates': '班组模板',
                'user.title': '用户',
                'user.admin': '管理员',
                'user.boss': '主管',
                'user.paramedic': '急救员',
                'user.emt': '急救技术员',
                'user.management': '用户管理',
                'timeoff.title': '休假',
                'timeoff.request': '申请休假',
                'timeoff.approved': '已批准',
                'timeoff.denied': '已拒绝',
                'timeoff.pending': '待审批',
                'notification.title': '通知',
                'notification.new': '新通知',
                'notification.read': '标记已读',
                'report.title': '报告',
                'report.export': '导出报告',
                'report.download': '下载',
                'settings.title': '设置',
                'settings.language': '语言',
                'settings.theme': '主题',
                'nav.scheduling': '排班管理',
                'nav.requests': '请求',
                'nav.staff': '人员管理',
                'nav.operations': '运营',
                'nav.analysis': '分析',
                'nav.calendar': '日历视图',
                'nav.trades': '换班',
                'nav.swap': '换班市场',
                'nav.availability': '可用性',
                'nav.training': '培训',
                'nav.bonus': '加班',
                'nav.callins': '紧急呼叫',
                'nav.absences': '缺勤',
                'nav.oncall': '值班轮换',
                'nav.analytics': '数据分析',
                'nav.history': '班次历史',
                'nav.notes': '主管备注',
                'nav.templates': '模板',
                'nav.payroll': '工资',
                'nav.locations': '站点',
                'nav.permissions': '权限',
                'error.required': '此字段为必填项',
                'error.invalid': '输入无效',
                'error.exists': '已存在',
                'error.notfound': '未找到'
            },
            ja: {
                'app.title': '救急車スケジュール管理システム',
                'app.welcome': 'ようこそ',
                'app.loading': '読み込み中...',
                'app.error': 'エラー',
                'app.success': '成功',
                'app.cancel': 'キャンセル',
                'app.save': '保存',
                'app.delete': '削除',
                'app.edit': '編集',
                'app.close': '閉じる',
                'app.submit': '送信',
                'app.search': '検索',
                'app.confirm': '確認',
                'app.back': '戻る',
                'app.next': '次へ',
                'app.yes': 'はい',
                'app.no': 'いいえ',
                'auth.login': 'ログイン',
                'auth.logout': 'ログアウト',
                'auth.username': 'ユーザー名',
                'auth.password': 'パスワード',
                'auth.login.success': 'ログイン成功',
                'auth.login.failed': 'ログイン失敗',
                'auth.logout.success': 'ログアウトしました',
                'dashboard.title': 'ダッシュボード',
                'dashboard.welcome': 'おかえりなさい',
                'dashboard.overview': '概要',
                'schedule.title': 'スケジュール',
                'schedule.create': 'スケジュール作成',
                'schedule.view': 'スケジュール表示',
                'schedule.draft': '下書き',
                'schedule.published': '公開済み',
                'schedule.archived': 'アーカイブ',
                'schedule.week': '週',
                'schedule.day': '日',
                'schedule.night': '夜',
                'shift.24hour': '24時間勤務',
                'shift.day': '日勤',
                'shift.night': '夜勤',
                'shift.evening': '準夜勤',
                'crew.title': 'クルー',
                'crew.create': 'クルー作成',
                'crew.manage': 'クルー管理',
                'crew.member': 'メンバー',
                'crew.templates': 'クルーテンプレート',
                'user.title': 'ユーザー',
                'user.admin': '管理者',
                'user.boss': '上司',
                'user.paramedic': '救急救命士',
                'user.emt': '救急隊員',
                'user.management': 'ユーザー管理',
                'timeoff.title': '休暇',
                'timeoff.request': '休暇申請',
                'timeoff.approved': '承認済み',
                'timeoff.denied': '却下',
                'timeoff.pending': '保留中',
                'notification.title': '通知',
                'notification.new': '新しい通知',
                'notification.read': '既読にする',
                'report.title': 'レポート',
                'report.export': 'レポート出力',
                'report.download': 'ダウンロード',
                'settings.title': '設定',
                'settings.language': '言語',
                'settings.theme': 'テーマ',
                'nav.scheduling': 'スケジュール管理',
                'nav.requests': 'リクエスト',
                'nav.staff': 'スタッフ管理',
                'nav.operations': '運用',
                'nav.analysis': '分析',
                'nav.calendar': 'カレンダー',
                'nav.trades': 'シフト交換',
                'nav.swap': '交換マーケット',
                'nav.availability': '空き状況',
                'nav.training': '研修',
                'nav.bonus': '残業',
                'nav.callins': '緊急呼出',
                'nav.absences': '欠勤',
                'nav.oncall': 'オンコール',
                'nav.analytics': '分析',
                'nav.history': 'シフト履歴',
                'nav.notes': '上司メモ',
                'nav.templates': 'テンプレート',
                'nav.payroll': '給与',
                'nav.locations': '拠点',
                'nav.permissions': '権限',
                'error.required': 'この項目は必須です',
                'error.invalid': '無効な入力',
                'error.exists': '既に存在します',
                'error.notfound': '見つかりません'
            },
            ar: {
                'app.title': 'نظام جدولة سيارات الإسعاف',
                'app.welcome': 'مرحباً',
                'app.loading': 'جاري التحميل...',
                'app.error': 'خطأ',
                'app.success': 'نجاح',
                'app.cancel': 'إلغاء',
                'app.save': 'حفظ',
                'app.delete': 'حذف',
                'app.edit': 'تعديل',
                'app.close': 'إغلاق',
                'app.submit': 'إرسال',
                'app.search': 'بحث',
                'app.confirm': 'تأكيد',
                'app.back': 'رجوع',
                'app.next': 'التالي',
                'app.yes': 'نعم',
                'app.no': 'لا',
                'auth.login': 'تسجيل الدخول',
                'auth.logout': 'تسجيل الخروج',
                'auth.username': 'اسم المستخدم',
                'auth.password': 'كلمة المرور',
                'auth.login.success': 'تم تسجيل الدخول بنجاح',
                'auth.login.failed': 'فشل تسجيل الدخول',
                'auth.logout.success': 'تم تسجيل الخروج بنجاح',
                'dashboard.title': 'لوحة التحكم',
                'dashboard.welcome': 'مرحباً بعودتك',
                'dashboard.overview': 'نظرة عامة',
                'schedule.title': 'الجدول',
                'schedule.create': 'إنشاء جدول',
                'schedule.view': 'عرض الجدول',
                'schedule.draft': 'مسودات',
                'schedule.published': 'منشورة',
                'schedule.archived': 'مؤرشفة',
                'schedule.week': 'أسبوع',
                'schedule.day': 'يوم',
                'schedule.night': 'ليل',
                'shift.24hour': 'نوبة 24 ساعة',
                'shift.day': 'نوبة نهارية',
                'shift.night': 'نوبة ليلية',
                'shift.evening': 'نوبة مسائية',
                'crew.title': 'الطاقم',
                'crew.create': 'إنشاء طاقم',
                'crew.manage': 'إدارة الطاقم',
                'crew.member': 'عضو',
                'crew.templates': 'قوالب الطاقم',
                'user.title': 'مستخدم',
                'user.admin': 'مدير',
                'user.boss': 'رئيس',
                'user.paramedic': 'مسعف',
                'user.emt': 'فني طوارئ',
                'user.management': 'إدارة المستخدمين',
                'timeoff.title': 'إجازة',
                'timeoff.request': 'طلب إجازة',
                'timeoff.approved': 'موافق عليه',
                'timeoff.denied': 'مرفوض',
                'timeoff.pending': 'قيد الانتظار',
                'notification.title': 'إشعارات',
                'notification.new': 'إشعار جديد',
                'notification.read': 'تحديد كمقروء',
                'report.title': 'تقارير',
                'report.export': 'تصدير التقرير',
                'report.download': 'تحميل',
                'settings.title': 'الإعدادات',
                'settings.language': 'اللغة',
                'settings.theme': 'المظهر',
                'nav.scheduling': 'الجدولة',
                'nav.requests': 'الطلبات',
                'nav.staff': 'إدارة الموظفين',
                'nav.operations': 'العمليات',
                'nav.analysis': 'التحليل',
                'nav.calendar': 'عرض التقويم',
                'nav.trades': 'تبادل النوبات',
                'nav.swap': 'سوق التبادل',
                'nav.availability': 'التوفر',
                'nav.training': 'التدريب',
                'nav.bonus': 'ساعات إضافية',
                'nav.callins': 'نداءات الطوارئ',
                'nav.absences': 'الغياب',
                'nav.oncall': 'المناوبة',
                'nav.analytics': 'التحليلات',
                'nav.history': 'سجل النوبات',
                'nav.notes': 'ملاحظات المشرف',
                'nav.templates': 'القوالب',
                'nav.payroll': 'الرواتب',
                'nav.locations': 'المواقع',
                'nav.permissions': 'الصلاحيات',
                'error.required': 'هذا الحقل مطلوب',
                'error.invalid': 'إدخال غير صالح',
                'error.exists': 'موجود بالفعل',
                'error.notfound': 'غير موجود'
            },
            pt: {
                'app.title': 'Sistema de Agendamento de Ambulâncias',
                'app.welcome': 'Bem-vindo',
                'app.loading': 'Carregando...',
                'app.error': 'Erro',
                'app.success': 'Sucesso',
                'app.cancel': 'Cancelar',
                'app.save': 'Salvar',
                'app.delete': 'Excluir',
                'app.edit': 'Editar',
                'app.close': 'Fechar',
                'app.submit': 'Enviar',
                'app.search': 'Pesquisar',
                'app.confirm': 'Confirmar',
                'app.back': 'Voltar',
                'app.next': 'Próximo',
                'app.yes': 'Sim',
                'app.no': 'Não',
                'auth.login': 'Entrar',
                'auth.logout': 'Sair',
                'auth.username': 'Usuário',
                'auth.password': 'Senha',
                'auth.login.success': 'Login realizado com sucesso',
                'auth.login.failed': 'Falha no login',
                'auth.logout.success': 'Logout realizado com sucesso',
                'dashboard.title': 'Painel',
                'dashboard.welcome': 'Bem-vindo de volta',
                'dashboard.overview': 'Visão Geral',
                'schedule.title': 'Escala',
                'schedule.create': 'Criar Escala',
                'schedule.view': 'Ver Escala',
                'schedule.draft': 'Rascunhos',
                'schedule.published': 'Publicadas',
                'schedule.archived': 'Arquivadas',
                'schedule.week': 'Semana',
                'schedule.day': 'Dia',
                'schedule.night': 'Noite',
                'shift.24hour': 'Plantão de 24 Horas',
                'shift.day': 'Plantão Diurno',
                'shift.night': 'Plantão Noturno',
                'shift.evening': 'Plantão Vespertino',
                'crew.title': 'Equipe',
                'crew.create': 'Criar Equipe',
                'crew.manage': 'Gerenciar Equipe',
                'crew.member': 'Membro',
                'crew.templates': 'Modelos de Equipe',
                'user.title': 'Usuário',
                'user.admin': 'Administrador',
                'user.boss': 'Chefe',
                'user.paramedic': 'Paramédico',
                'user.emt': 'Técnico',
                'user.management': 'Gerenciamento de Usuários',
                'timeoff.title': 'Folga',
                'timeoff.request': 'Solicitar Folga',
                'timeoff.approved': 'Aprovado',
                'timeoff.denied': 'Negado',
                'timeoff.pending': 'Pendente',
                'notification.title': 'Notificações',
                'notification.new': 'Nova notificação',
                'notification.read': 'Marcar como lido',
                'report.title': 'Relatórios',
                'report.export': 'Exportar Relatório',
                'report.download': 'Baixar',
                'settings.title': 'Configurações',
                'settings.language': 'Idioma',
                'settings.theme': 'Tema',
                'nav.scheduling': 'Agendamento',
                'nav.requests': 'Solicitações',
                'nav.staff': 'Gestão de Pessoal',
                'nav.operations': 'Operações',
                'nav.analysis': 'Análise',
                'nav.calendar': 'Calendário',
                'nav.trades': 'Troca de Plantão',
                'nav.swap': 'Mercado de Trocas',
                'nav.availability': 'Disponibilidade',
                'nav.training': 'Treinamento',
                'nav.bonus': 'Horas Extras',
                'nav.callins': 'Chamadas de Emergência',
                'nav.absences': 'Ausências',
                'nav.oncall': 'Plantão',
                'nav.analytics': 'Análises',
                'nav.history': 'Histórico de Plantões',
                'nav.notes': 'Notas do Supervisor',
                'nav.templates': 'Modelos',
                'nav.payroll': 'Folha de Pagamento',
                'nav.locations': 'Locais',
                'nav.permissions': 'Permissões',
                'error.required': 'Este campo é obrigatório',
                'error.invalid': 'Entrada inválida',
                'error.exists': 'Já existe',
                'error.notfound': 'Não encontrado'
            },
            ko: {
                'app.title': '구급차 스케줄링 시스템',
                'app.welcome': '환영합니다',
                'app.loading': '로딩 중...',
                'app.error': '오류',
                'app.success': '성공',
                'app.cancel': '취소',
                'app.save': '저장',
                'app.delete': '삭제',
                'app.edit': '편집',
                'app.close': '닫기',
                'app.submit': '제출',
                'app.search': '검색',
                'app.confirm': '확인',
                'app.back': '뒤로',
                'app.next': '다음',
                'app.yes': '예',
                'app.no': '아니오',
                'auth.login': '로그인',
                'auth.logout': '로그아웃',
                'auth.username': '사용자명',
                'auth.password': '비밀번호',
                'auth.login.success': '로그인 성공',
                'auth.login.failed': '로그인 실패',
                'auth.logout.success': '로그아웃 완료',
                'dashboard.title': '대시보드',
                'dashboard.welcome': '다시 오신 것을 환영합니다',
                'dashboard.overview': '개요',
                'schedule.title': '스케줄',
                'schedule.create': '스케줄 생성',
                'schedule.view': '스케줄 보기',
                'schedule.draft': '초안',
                'schedule.published': '게시됨',
                'schedule.archived': '보관됨',
                'schedule.week': '주',
                'schedule.day': '일',
                'schedule.night': '야간',
                'shift.24hour': '24시간 근무',
                'shift.day': '주간 근무',
                'shift.night': '야간 근무',
                'shift.evening': '저녁 근무',
                'crew.title': '팀',
                'crew.create': '팀 생성',
                'crew.manage': '팀 관리',
                'crew.member': '팀원',
                'crew.templates': '팀 템플릿',
                'user.title': '사용자',
                'user.admin': '관리자',
                'user.boss': '상사',
                'user.paramedic': '응급구조사',
                'user.emt': '응급의료기사',
                'user.management': '사용자 관리',
                'timeoff.title': '휴가',
                'timeoff.request': '휴가 신청',
                'timeoff.approved': '승인됨',
                'timeoff.denied': '거부됨',
                'timeoff.pending': '대기 중',
                'notification.title': '알림',
                'notification.new': '새 알림',
                'notification.read': '읽음 표시',
                'report.title': '보고서',
                'report.export': '보고서 내보내기',
                'report.download': '다운로드',
                'settings.title': '설정',
                'settings.language': '언어',
                'settings.theme': '테마',
                'nav.scheduling': '스케줄 관리',
                'nav.requests': '요청',
                'nav.staff': '직원 관리',
                'nav.operations': '운영',
                'nav.analysis': '분석',
                'nav.calendar': '캘린더',
                'nav.trades': '근무 교환',
                'nav.swap': '교환 마켓',
                'nav.availability': '가용성',
                'nav.training': '교육',
                'nav.bonus': '초과근무',
                'nav.callins': '긴급 호출',
                'nav.absences': '결근',
                'nav.oncall': '대기 근무',
                'nav.analytics': '분석',
                'nav.history': '근무 이력',
                'nav.notes': '관리자 메모',
                'nav.templates': '템플릿',
                'nav.payroll': '급여',
                'nav.locations': '위치',
                'nav.permissions': '권한',
                'error.required': '필수 항목입니다',
                'error.invalid': '잘못된 입력',
                'error.exists': '이미 존재합니다',
                'error.notfound': '찾을 수 없습니다'
            },
            it: {
                'app.title': 'Sistema di Pianificazione Ambulanze',
                'app.welcome': 'Benvenuto',
                'app.loading': 'Caricamento...',
                'app.error': 'Errore',
                'app.success': 'Successo',
                'app.cancel': 'Annulla',
                'app.save': 'Salva',
                'app.delete': 'Elimina',
                'app.edit': 'Modifica',
                'app.close': 'Chiudi',
                'app.submit': 'Invia',
                'app.search': 'Cerca',
                'app.confirm': 'Conferma',
                'app.back': 'Indietro',
                'app.next': 'Avanti',
                'app.yes': 'Sì',
                'app.no': 'No',
                'auth.login': 'Accedi',
                'auth.logout': 'Esci',
                'auth.username': 'Nome utente',
                'auth.password': 'Password',
                'auth.login.success': 'Accesso riuscito',
                'auth.login.failed': 'Accesso fallito',
                'auth.logout.success': 'Disconnessione riuscita',
                'dashboard.title': 'Pannello di Controllo',
                'dashboard.welcome': 'Bentornato',
                'dashboard.overview': 'Panoramica',
                'schedule.title': 'Turni',
                'schedule.create': 'Crea Turno',
                'schedule.view': 'Visualizza Turno',
                'schedule.draft': 'Bozze',
                'schedule.published': 'Pubblicati',
                'schedule.archived': 'Archiviati',
                'schedule.week': 'Settimana',
                'schedule.day': 'Giorno',
                'schedule.night': 'Notte',
                'shift.24hour': 'Turno di 24 Ore',
                'shift.day': 'Turno Diurno',
                'shift.night': 'Turno Notturno',
                'shift.evening': 'Turno Serale',
                'crew.title': 'Equipaggio',
                'crew.create': 'Crea Equipaggio',
                'crew.manage': 'Gestisci Equipaggio',
                'crew.member': 'Membro',
                'crew.templates': 'Modelli Equipaggio',
                'user.title': 'Utente',
                'user.admin': 'Amministratore',
                'user.boss': 'Capo',
                'user.paramedic': 'Paramedico',
                'user.emt': 'Tecnico',
                'user.management': 'Gestione Utenti',
                'timeoff.title': 'Ferie',
                'timeoff.request': 'Richiedi Ferie',
                'timeoff.approved': 'Approvato',
                'timeoff.denied': 'Rifiutato',
                'timeoff.pending': 'In attesa',
                'notification.title': 'Notifiche',
                'notification.new': 'Nuova notifica',
                'notification.read': 'Segna come letto',
                'report.title': 'Report',
                'report.export': 'Esporta Report',
                'report.download': 'Scarica',
                'settings.title': 'Impostazioni',
                'settings.language': 'Lingua',
                'settings.theme': 'Tema',
                'nav.scheduling': 'Pianificazione',
                'nav.requests': 'Richieste',
                'nav.staff': 'Gestione Personale',
                'nav.operations': 'Operazioni',
                'nav.analysis': 'Analisi',
                'nav.calendar': 'Calendario',
                'nav.trades': 'Scambio Turni',
                'nav.swap': 'Mercato Scambi',
                'nav.availability': 'Disponibilità',
                'nav.training': 'Formazione',
                'nav.bonus': 'Straordinari',
                'nav.callins': 'Chiamate Emergenza',
                'nav.absences': 'Assenze',
                'nav.oncall': 'Reperibilità',
                'nav.analytics': 'Analisi',
                'nav.history': 'Storico Turni',
                'nav.notes': 'Note Supervisore',
                'nav.templates': 'Modelli',
                'nav.payroll': 'Buste Paga',
                'nav.locations': 'Sedi',
                'nav.permissions': 'Permessi',
                'error.required': 'Questo campo è obbligatorio',
                'error.invalid': 'Input non valido',
                'error.exists': 'Esiste già',
                'error.notfound': 'Non trovato'
            },
            ru: {
                'app.title': 'Система планирования скорой помощи',
                'app.welcome': 'Добро пожаловать',
                'app.loading': 'Загрузка...',
                'app.error': 'Ошибка',
                'app.success': 'Успех',
                'app.cancel': 'Отмена',
                'app.save': 'Сохранить',
                'app.delete': 'Удалить',
                'app.edit': 'Редактировать',
                'app.close': 'Закрыть',
                'app.submit': 'Отправить',
                'app.search': 'Поиск',
                'app.confirm': 'Подтвердить',
                'app.back': 'Назад',
                'app.next': 'Далее',
                'app.yes': 'Да',
                'app.no': 'Нет',
                'auth.login': 'Войти',
                'auth.logout': 'Выйти',
                'auth.username': 'Имя пользователя',
                'auth.password': 'Пароль',
                'auth.login.success': 'Вход выполнен успешно',
                'auth.login.failed': 'Ошибка входа',
                'auth.logout.success': 'Выход выполнен успешно',
                'dashboard.title': 'Панель управления',
                'dashboard.welcome': 'С возвращением',
                'dashboard.overview': 'Обзор',
                'schedule.title': 'Расписание',
                'schedule.create': 'Создать расписание',
                'schedule.view': 'Просмотр расписания',
                'schedule.draft': 'Черновики',
                'schedule.published': 'Опубликованные',
                'schedule.archived': 'Архив',
                'schedule.week': 'Неделя',
                'schedule.day': 'День',
                'schedule.night': 'Ночь',
                'shift.24hour': '24-часовая смена',
                'shift.day': 'Дневная смена',
                'shift.night': 'Ночная смена',
                'shift.evening': 'Вечерняя смена',
                'crew.title': 'Бригада',
                'crew.create': 'Создать бригаду',
                'crew.manage': 'Управление бригадой',
                'crew.member': 'Член бригады',
                'crew.templates': 'Шаблоны бригад',
                'user.title': 'Пользователь',
                'user.admin': 'Администратор',
                'user.boss': 'Руководитель',
                'user.paramedic': 'Фельдшер',
                'user.emt': 'Санитар',
                'user.management': 'Управление пользователями',
                'timeoff.title': 'Отпуск',
                'timeoff.request': 'Запросить отпуск',
                'timeoff.approved': 'Одобрено',
                'timeoff.denied': 'Отклонено',
                'timeoff.pending': 'На рассмотрении',
                'notification.title': 'Уведомления',
                'notification.new': 'Новое уведомление',
                'notification.read': 'Отметить как прочитанное',
                'report.title': 'Отчёты',
                'report.export': 'Экспорт отчёта',
                'report.download': 'Скачать',
                'settings.title': 'Настройки',
                'settings.language': 'Язык',
                'settings.theme': 'Тема',
                'nav.scheduling': 'Планирование',
                'nav.requests': 'Запросы',
                'nav.staff': 'Управление персоналом',
                'nav.operations': 'Операции',
                'nav.analysis': 'Анализ',
                'nav.calendar': 'Календарь',
                'nav.trades': 'Обмен сменами',
                'nav.swap': 'Биржа обмена',
                'nav.availability': 'Доступность',
                'nav.training': 'Обучение',
                'nav.bonus': 'Сверхурочные',
                'nav.callins': 'Экстренные вызовы',
                'nav.absences': 'Отсутствия',
                'nav.oncall': 'Дежурство',
                'nav.analytics': 'Аналитика',
                'nav.history': 'История смен',
                'nav.notes': 'Заметки руководителя',
                'nav.templates': 'Шаблоны',
                'nav.payroll': 'Зарплата',
                'nav.locations': 'Станции',
                'nav.permissions': 'Права доступа',
                'error.required': 'Это поле обязательно',
                'error.invalid': 'Неверный ввод',
                'error.exists': 'Уже существует',
                'error.notfound': 'Не найдено'
            },
            hi: {
                'app.title': 'एम्बुलेंस शेड्यूलिंग सिस्टम',
                'app.welcome': 'स्वागत है',
                'app.loading': 'लोड हो रहा है...',
                'app.error': 'त्रुटि',
                'app.success': 'सफल',
                'app.cancel': 'रद्द करें',
                'app.save': 'सहेजें',
                'app.delete': 'हटाएं',
                'app.edit': 'संपादित करें',
                'app.close': 'बंद करें',
                'app.submit': 'जमा करें',
                'app.search': 'खोजें',
                'app.confirm': 'पुष्टि करें',
                'app.back': 'वापस',
                'app.next': 'अगला',
                'app.yes': 'हाँ',
                'app.no': 'नहीं',
                'auth.login': 'लॉगिन',
                'auth.logout': 'लॉगआउट',
                'auth.username': 'उपयोगकर्ता नाम',
                'auth.password': 'पासवर्ड',
                'auth.login.success': 'लॉगिन सफल',
                'auth.login.failed': 'लॉगिन विफल',
                'auth.logout.success': 'सफलतापूर्वक लॉगआउट',
                'dashboard.title': 'डैशबोर्ड',
                'dashboard.welcome': 'वापसी पर स्वागत है',
                'dashboard.overview': 'अवलोकन',
                'schedule.title': 'शेड्यूल',
                'schedule.create': 'शेड्यूल बनाएं',
                'schedule.view': 'शेड्यूल देखें',
                'schedule.draft': 'ड्राफ्ट',
                'schedule.published': 'प्रकाशित',
                'schedule.archived': 'संग्रहीत',
                'schedule.week': 'सप्ताह',
                'schedule.day': 'दिन',
                'schedule.night': 'रात',
                'shift.24hour': '24 घंटे की शिफ्ट',
                'shift.day': 'दिन की शिफ्ट',
                'shift.night': 'रात की शिफ्ट',
                'shift.evening': 'शाम की शिफ्ट',
                'crew.title': 'दल',
                'crew.create': 'दल बनाएं',
                'crew.manage': 'दल प्रबंधन',
                'crew.member': 'सदस्य',
                'crew.templates': 'दल टेम्पलेट',
                'user.title': 'उपयोगकर्ता',
                'user.admin': 'प्रशासक',
                'user.boss': 'प्रमुख',
                'user.paramedic': 'पैरामेडिक',
                'user.emt': 'ईएमटी',
                'user.management': 'उपयोगकर्ता प्रबंधन',
                'timeoff.title': 'छुट्टी',
                'timeoff.request': 'छुट्टी का अनुरोध',
                'timeoff.approved': 'स्वीकृत',
                'timeoff.denied': 'अस्वीकृत',
                'timeoff.pending': 'लंबित',
                'notification.title': 'सूचनाएं',
                'notification.new': 'नई सूचना',
                'notification.read': 'पढ़ा हुआ चिह्नित करें',
                'report.title': 'रिपोर्ट',
                'report.export': 'रिपोर्ट निर्यात',
                'report.download': 'डाउनलोड',
                'settings.title': 'सेटिंग्स',
                'settings.language': 'भाषा',
                'settings.theme': 'थीम',
                'nav.scheduling': 'शेड्यूलिंग',
                'nav.requests': 'अनुरोध',
                'nav.staff': 'कर्मचारी प्रबंधन',
                'nav.operations': 'संचालन',
                'nav.analysis': 'विश्लेषण',
                'nav.calendar': 'कैलेंडर',
                'nav.trades': 'शिफ्ट विनिमय',
                'nav.swap': 'विनिमय बाज़ार',
                'nav.availability': 'उपलब्धता',
                'nav.training': 'प्रशिक्षण',
                'nav.bonus': 'ओवरटाइम',
                'nav.callins': 'आपातकालीन कॉल',
                'nav.absences': 'अनुपस्थिति',
                'nav.oncall': 'ऑन-कॉल',
                'nav.analytics': 'विश्लेषिकी',
                'nav.history': 'शिफ्ट इतिहास',
                'nav.notes': 'पर्यवेक्षक नोट्स',
                'nav.templates': 'टेम्पलेट',
                'nav.payroll': 'वेतन',
                'nav.locations': 'स्थान',
                'nav.permissions': 'अनुमतियाँ',
                'error.required': 'यह फ़ील्ड आवश्यक है',
                'error.invalid': 'अमान्य इनपुट',
                'error.exists': 'पहले से मौजूद है',
                'error.notfound': 'नहीं मिला'
            },
            tr: {
                'app.title': 'Ambulans Planlama Sistemi',
                'app.welcome': 'Hoş geldiniz',
                'app.loading': 'Yükleniyor...',
                'app.error': 'Hata',
                'app.success': 'Başarılı',
                'app.cancel': 'İptal',
                'app.save': 'Kaydet',
                'app.delete': 'Sil',
                'app.edit': 'Düzenle',
                'app.close': 'Kapat',
                'app.submit': 'Gönder',
                'app.search': 'Ara',
                'app.confirm': 'Onayla',
                'app.back': 'Geri',
                'app.next': 'İleri',
                'app.yes': 'Evet',
                'app.no': 'Hayır',
                'auth.login': 'Giriş Yap',
                'auth.logout': 'Çıkış Yap',
                'auth.username': 'Kullanıcı Adı',
                'auth.password': 'Şifre',
                'auth.login.success': 'Giriş başarılı',
                'auth.login.failed': 'Giriş başarısız',
                'auth.logout.success': 'Çıkış başarılı',
                'dashboard.title': 'Kontrol Paneli',
                'dashboard.welcome': 'Tekrar hoş geldiniz',
                'dashboard.overview': 'Genel Bakış',
                'schedule.title': 'Program',
                'schedule.create': 'Program Oluştur',
                'schedule.view': 'Programı Görüntüle',
                'schedule.draft': 'Taslaklar',
                'schedule.published': 'Yayınlanan',
                'schedule.archived': 'Arşivlenen',
                'schedule.week': 'Hafta',
                'schedule.day': 'Gün',
                'schedule.night': 'Gece',
                'shift.24hour': '24 Saat Nöbet',
                'shift.day': 'Gündüz Nöbeti',
                'shift.night': 'Gece Nöbeti',
                'shift.evening': 'Akşam Nöbeti',
                'crew.title': 'Ekip',
                'crew.create': 'Ekip Oluştur',
                'crew.manage': 'Ekip Yönetimi',
                'crew.member': 'Üye',
                'crew.templates': 'Ekip Şablonları',
                'user.title': 'Kullanıcı',
                'user.admin': 'Yönetici',
                'user.boss': 'Şef',
                'user.paramedic': 'Paramedik',
                'user.emt': 'Acil Tıp Teknisyeni',
                'user.management': 'Kullanıcı Yönetimi',
                'timeoff.title': 'İzin',
                'timeoff.request': 'İzin Talebi',
                'timeoff.approved': 'Onaylandı',
                'timeoff.denied': 'Reddedildi',
                'timeoff.pending': 'Beklemede',
                'notification.title': 'Bildirimler',
                'notification.new': 'Yeni bildirim',
                'notification.read': 'Okundu işaretle',
                'report.title': 'Raporlar',
                'report.export': 'Rapor Dışa Aktar',
                'report.download': 'İndir',
                'settings.title': 'Ayarlar',
                'settings.language': 'Dil',
                'settings.theme': 'Tema',
                'nav.scheduling': 'Planlama',
                'nav.requests': 'Talepler',
                'nav.staff': 'Personel Yönetimi',
                'nav.operations': 'Operasyonlar',
                'nav.analysis': 'Analiz',
                'nav.calendar': 'Takvim',
                'nav.trades': 'Nöbet Değişimi',
                'nav.swap': 'Değişim Pazarı',
                'nav.availability': 'Müsaitlik',
                'nav.training': 'Eğitim',
                'nav.bonus': 'Fazla Mesai',
                'nav.callins': 'Acil Çağrılar',
                'nav.absences': 'Devamsızlıklar',
                'nav.oncall': 'Nöbet Rotasyonu',
                'nav.analytics': 'Analitik',
                'nav.history': 'Nöbet Geçmişi',
                'nav.notes': 'Yönetici Notları',
                'nav.templates': 'Şablonlar',
                'nav.payroll': 'Bordro',
                'nav.locations': 'Konumlar',
                'nav.permissions': 'İzinler',
                'error.required': 'Bu alan zorunludur',
                'error.invalid': 'Geçersiz giriş',
                'error.exists': 'Zaten mevcut',
                'error.notfound': 'Bulunamadı'
            }
        };
    },

    /** Get translated text */
    translate(key) {
        const lang = this.translations[this.currentLanguage];
        if (lang && lang[key]) return lang[key];
        if (this.translations.en && this.translations.en[key]) return this.translations.en[key];
        return key;
    },

    /** Shorthand alias */
    t(key) {
        return this.translate(key);
    },

    /** Apply translations to the page */
    applyTranslations() {
        // Update elements with data-i18n attribute
        const elements = document.querySelectorAll('[data-i18n]');
        for (const i = 0; i < elements.length; i++) {
            const key = elements[i].getAttribute('data-i18n');
            elements[i].textContent = this.translate(key);
        }

        // Update placeholders
        const inputs = document.querySelectorAll('[data-i18n-placeholder]');
        for (const j = 0; j < inputs.length; j++) {
            const pKey = inputs[j].getAttribute('data-i18n-placeholder');
            inputs[j].placeholder = this.translate(pKey);
        }

        // Update titles
        const titledElements = document.querySelectorAll('[data-i18n-title]');
        for (const k = 0; k < titledElements.length; k++) {
            const tKey = titledElements[k].getAttribute('data-i18n-title');
            titledElements[k].title = this.translate(tKey);
        }

        // Update document title
        document.title = this.translate('app.title');

        // Set RTL for Arabic
        if (this.currentLanguage === 'ar') {
            document.documentElement.setAttribute('dir', 'rtl');
        } else {
            document.documentElement.setAttribute('dir', 'ltr');
        }
    },

    /** Switch language */
    switchLanguage(language) {
        if (this.supportedLanguages.indexOf(language) !== -1) {
            this.currentLanguage = language;
            localStorage.setItem('preferredLanguage', language);
            this.applyTranslations();
            this.updateLanguageSwitcher();

            if (typeof AccessibilityEnhancer !== 'undefined' && typeof AccessibilityEnhancer.announce === 'function') {
                AccessibilityEnhancer.announce('Language changed to ' + this.getLanguageName(language));
            }
        }
    },

    /** Add language switcher to the UI */
    addLanguageSwitcher() {
        const switcher = document.getElementById('language-switcher');
        if (switcher) return; // Already exists

        switcher = document.createElement('div');
        switcher.id = 'language-switcher';
        switcher.className = 'language-switcher';

        const optionsHtml = '';
        for (const i = 0; i < this.supportedLanguages.length; i++) {
            const lang = this.supportedLanguages[i];
            optionsHtml += '<option value="' + lang + '"' + (lang === this.currentLanguage ? ' selected' : '') + '>' + this.getLanguageName(lang) + '</option>';
        }

        switcher.innerHTML = '<select id="language-select" aria-label="Select language">' + optionsHtml + '</select>';

        // Add styles
        const style = document.createElement('style');
        style.textContent = '.language-switcher{position:fixed;top:10px;right:10px;z-index:1000;}' +
            '#language-select{padding:6px 10px;border-radius:6px;border:1px solid var(--border-color,#ccc);background:var(--bg-secondary,#fff);color:var(--text-primary,#333);cursor:pointer;font-size:0.85rem;}' +
            '[dir="rtl"] .language-switcher{right:auto;left:10px;}';
        document.head.appendChild(style);

        document.body.appendChild(switcher);

        // Add event listener
        const self = this;
        setTimeout(function() {
            const select = document.getElementById('language-select');
            if (select) {
                select.addEventListener('change', function(e) {
                    self.switchLanguage(e.target.value);
                });
            }
        }, 100);
    },

    /** Get language display name */
    getLanguageName(code) {
        const names = {
            en: 'English',
            es: 'Español',
            fr: 'Français',
            de: 'Deutsch',
            zh: '中文',
            ja: '日本語',
            ar: 'العربية',
            pt: 'Português',
            ko: '한국어',
            it: 'Italiano',
            ru: 'Русский',
            hi: 'हिन्दी',
            tr: 'Türkçe'
        };
        return names[code] || code;
    },

    /** Update language switcher display */
    updateLanguageSwitcher() {
        const select = document.getElementById('language-select');
        if (select) {
            select.value = this.currentLanguage;
        }
    }
};

// Auto-initialize when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function() { I18n.init(); });
} else {
    I18n.init();
}